App\DTO\Request\UserRegistration:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
      - App\Validator\Constraint\UniqueEmail: ~
      - Length:
          max: 180

    password:
      - NotBlank: ~
      - Type: string
      - Length:
          min: 8
          max: 64

    firstName:
      - NotBlank: ~
      - Type: string
      - Length:
          min: 1
          max: 60

    lastName:
      - NotBlank: ~
      - Type: string
      - Length:
          min: 1
          max: 60

    timezone:
      - Timezone: ~