services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $tokenLifetime: '%jwt_token_lifetime%'
      $tokenType: '%jwt_token_type%'
      $cryptoNonce: '%app.crypto.nonce%'
      $cryptoKey: '%app.crypto.key%'

  Symfony\Component\Serializer\Serializer: ~
  App\Component\Serializer:
    decorates: Symfony\Component\Serializer\Serializer
    arguments: ['@App\Component\Serializer.inner']

  App\Component\RequestMapper: ~

  App\Component\Http\HttpErrorConfigProvider:
    arguments: ['%http_exceptions%']

  App\Component\Http\HttpErrorFormatter: ~

  App\Security\CryptoSecret: ~

  App\Security\Encoder\MessageEncoder: ~
  App\Security\Encoder\MessageEncoderInterface: '@App\Security\Encoder\MessageEncoder'

  App\Security\Decoder\MessageDecoder: ~
  App\Security\Decoder\MessageDecoderInterface: '@App\Security\Decoder\MessageDecoder'

  App\Listener\JwtSubscriber: ~
  App\Listener\KernelSubscriber: ~

  App\Service\MessageService: ~
  App\Service\UserRegistrationService: ~

  App\Repository\MessageRepository: ~
  App\Repository\UserRepository: ~