parameters:
    jwt_token_lifetime: 3600
    jwt_token_type: 'Bearer'

lexik_jwt_authentication:
    secret_key: '%env(string:JWT_KEY_PATH)%/private.pem'
    public_key: '%env(string:JWT_KEY_PATH)%/public.pem'
    pass_phrase: '%env(string:JWT_KEY_PASS)%'
    token_ttl: '%jwt_token_lifetime%'
